name: Build Buyers Guide PDF

on:
  push:
    branches: [ main ]
    paths:
      - buyers_guide.md
      - metadata.yaml
      - assets/**
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    container: pandoc/latex:3.7

    steps:
      - uses: actions/checkout@v4

      - name: Install KOMA-Script (scrartcl.cls)
        run: |
          tlmgr update --self --all
          tlmgr install koma-script \
                        footnotebackref \
                        mdframed \
                        zref \
                        needspace \
                        sourcesanspro \
                        xkeyval \
                        sourcecodepro \
                        titling \
                        pagecolor

      - name: Fetch Eisvogel template
        run: |
          mkdir -p .pandoc/templates
          curl -sSL \
            https://github.com/Wandmalfarbe/pandoc-latex-template/releases/download/v3.2.0/Eisvogel-3.2.0.tar.gz \
            -o Eisvogel.tar.gz
          tar xf Eisvogel.tar.gz && rm Eisvogel.tar.gz

      # ---- Build PDF ----
      - name: Build PDF
        run: |
          pandoc buyers_guide.md \
            --template=Eisvogel-3.2.0/eisvogel.latex \
            --metadata-file=metadata.yaml \
            --pdf-engine=xelatex \
            -o buyers_guide.pdf

      # ---- Publish artifact ----
      - uses: actions/upload-artifact@v4
        with:
          name: buyers-guide-pdf
          path: buyers_guide.pdf

      # ---- Create/Update 'dev' tag ----
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create or update 'dev' tag and push
        run: |
          git fetch --tags
          git tag -f dev
          git push origin dev --force

      # ---- Create or update GitHub Release with PDF asset ----
      - name: Create or update release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: dev
          name: "Development Build"
          body: "Always up-to-date buyers_guide.pdf"
          draft: false
          prerelease: true
          files: buyers_guide.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
